name: ROS2 CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
          rosdistro: [master]
          os: [ubuntu-18.04, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - if: runner.os == 'Linux'
      # azure ubuntu repo can be flaky so add an alternate source
      run: sed -e 's/azure.archive.ubuntu.com/us.archive.ubuntu.com/g' -e t -e d /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/nonazure.list
    - name: Acquire ROS dependencies
      uses: ros-tooling/setup-ros@0.0.19
    - name: Build and test ROS
      uses: ros-tooling/action-ros-ci@0.0.15
      with:
        package-name: |
          rmw_cyclonedds_cpp
          test_cli
          test_cli_remapping
          test_communication
          test_quality_of_service
          test_rclcpp
          test_security
        vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/${{ matrix.rosdistro }}/ros2.repos
    - name: run integra
