name: ROS 2 CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
          rosdistro: [rolling]
          os: [ubuntu-18.04, ubuntu-20.04, macOS-latest, windows-latest]
          include:
          - rosdistro: rolling
            repos_branch: master
    runs-on: ${{ matrix.os }}
    steps:
    - if: runner.os == 'Windows'
      uses: actions/cache@v1
      with:
        path: ${{env.TEMP}}/chocolatey
        key: ${{matrix.os}}-chocolatey-${{github.job_id}}
        restore-keys: ${{matrix.os}}-chocolatey-
    - if: runner.os == 'Linux'
      # azure ubuntu repo can be flaky so add an alternate source
      run: sed -e 's/azure.archive.ubuntu.com/us.archive.ubuntu.com/g' -e t -e d /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/nonazure.list
    - name: Acquire ROS dependencies
      uses: ros-tooling/setup-ros@master
    - name: Build and test ROS
      id: ros_ci
      uses: ros-tooling/action-ros-ci@0.0.19
      env:
        CMAKE_CONFIG_TYPE: Debug
      with:
        package-name: >
          rmw_cyclonedds_cpp
          rmw_implementation
        target-ros2-distro: ${{matrix.rosdistro}}
        vcs-repo-file-url: >
          https://raw.githubusercontent.com/ros2/ros2/${{ matrix.repos_branch }}/ros2.repos
          https://raw.githubusercontent.com/${{github.repository}}/${{github.sha}}/.github/resources/suppress_other_rmw.repos
