name: ROS2 CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
          rosdistro: [foxy]
          os: [ubuntu-20.04, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
    - if: runner.os == 'Windows'
      uses: actions/cache@v1
      with:
        path: ${{env.TEMP}}/chocolatey
        key: ${{matrix.os}}-chocolatey-${{github.job_id}}
        restore-keys: ${{matrix.os}}-chocolatey-
    - if: runner.os == 'Linux'
      # azure ubuntu repo can be flaky so add an alternate source
      run: sed -e 's/azure.archive.ubuntu.com/us.archive.ubuntu.com/g' -e t -e d /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/nonazure.list
    - if: runner.os == 'Windows'
      name: Pin pip
      run: python -m pip install -U pip==21.3.1
    - name: Acquire ROS dependencies
      uses: ros-tooling/setup-ros@v0.2
      with:
        use-ros2-testing: true
        required-ros-distributions: foxy
    - name: Set up git to see all pull requests
      run: git config --global --add remote.origin.fetch '+refs/pull/*:refs/remotes/origin/pull/*'
    - name: Build and test ROS
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        target-ros2-distro: foxy
        package-name: >
          rmw_cyclonedds_cpp
          rmw_implementation
        vcs-repo-file-url: >
          https://raw.githubusercontent.com/ros2/ros2/${{ matrix.rosdistro }}/ros2.repos
          https://raw.githubusercontent.com/${{github.repository}}/${{github.sha}}/.github/resources/local.repos
